version: "3.7"

x-redis-base: &redis-base
  image: docker.io/bitnami/redis-cluster:7.0.10

services:
  redis-node-0:
    container_name: redis-node-0
    <<: *redis-base
    ports:
      - 6370:6370
      - 16370:16370
    environment:
      REDIS_CLUSTER_DYNAMIC_IPS: no
      REDIS_CLUSTER_ANNOUNCE_IP: 10.251.1.2
      REDIS_PORT_NUMBER: 6370
      ALLOW_EMPTY_PASSWORD: yes
      REDIS_NODES: 10.251.1.2:6370 10.251.1.2:6371 10.251.1.2:6372 10.251.1.2:6373 10.251.1.2:6374 10.251.1.2:6375
  redis-node-1:
    container_name: redis-node-1
    <<: *redis-base
    ports:
      - 6371:6371
      - 16371:16371
    environment:
      REDIS_CLUSTER_DYNAMIC_IPS: no
      REDIS_CLUSTER_ANNOUNCE_IP: 10.251.1.2
      REDIS_PORT_NUMBER: 6371
      ALLOW_EMPTY_PASSWORD: yes
      REDIS_NODES: 10.251.1.2:6370 10.251.1.2:6371 10.251.1.2:6372 10.251.1.2:6373 10.251.1.2:6374 10.251.1.2:6375
  redis-node-2:
    container_name: redis-node-2
    <<: *redis-base
    ports:
      - 6372:6372
      - 16372:16372
    environment:
      REDIS_CLUSTER_DYNAMIC_IPS: no
      REDIS_CLUSTER_ANNOUNCE_IP: 10.251.1.2
      REDIS_PORT_NUMBER: 6372
      ALLOW_EMPTY_PASSWORD: yes
      REDIS_NODES: 10.251.1.2:6370 10.251.1.2:6371 10.251.1.2:6372 10.251.1.2:6373 10.251.1.2:6374 10.251.1.2:6375
  redis-node-3:
    container_name: redis-node-3
    <<: *redis-base
    ports:
      - 6373:6373
      - 16373:16373
    environment:
      REDIS_CLUSTER_DYNAMIC_IPS: no
      REDIS_CLUSTER_ANNOUNCE_IP: 10.251.1.2
      REDIS_PORT_NUMBER: 6373
      ALLOW_EMPTY_PASSWORD: yes
      REDIS_NODES: 10.251.1.2:6370 10.251.1.2:6371 10.251.1.2:6372 10.251.1.2:6373 10.251.1.2:6374 10.251.1.2:6375
  redis-node-4:
    container_name: redis-node-4
    <<: *redis-base
    ports:
      - 6374:6374
      - 16374:16374
    environment:
      REDIS_CLUSTER_DYNAMIC_IPS: no
      REDIS_CLUSTER_ANNOUNCE_IP: 10.251.1.2
      REDIS_PORT_NUMBER: 6374
      ALLOW_EMPTY_PASSWORD: yes
      REDIS_NODES: 10.251.1.2:6370 10.251.1.2:6371 10.251.1.2:6372 10.251.1.2:6373 10.251.1.2:6374 10.251.1.2:6375
  redis-node-5:
    container_name: redis-node-5
    <<: *redis-base
    ports:
      - 6375:6375
      - 16375:16375
    environment:
      REDIS_CLUSTER_DYNAMIC_IPS: no
      REDIS_CLUSTER_ANNOUNCE_IP: 10.251.1.2
      REDIS_PORT_NUMBER: 6375
      ALLOW_EMPTY_PASSWORD: yes
      REDIS_NODES: 10.251.1.2:6370 10.251.1.2:6371 10.251.1.2:6372 10.251.1.2:6373 10.251.1.2:6374 10.251.1.2:6375
      REDIS_CLUSTER_REPLICAS: 1
      REDIS_CLUSTER_CREATOR: yes
